version: "3"

services:
  php:
    build:
      context: ./php
    container_name: project_php
    volumes:
      - ../app:/var/www/symfony
    networks:
      - symfony_app
  nginx:
    build:
      context: ./nginx
    container_name: project_nginx
    volumes:
      - ../app:/var/www/symfony
    ports:
      - 8080:80
    networks:
      - symfony_app

networks:
  symfony_app: